### ISSUE TITLE
[Document Request] Allow user specify OS disk size alongside OS image

### ISSUE THREAD

**Issue by hcoona** [microsoft/lisa#2903]
Hi LISA team,

I'd like to request a new feature to allow user specify OS disk size alongside OS image. Allowing user to specify OS image is a great feature to let user establish a basic environment for testing by burn necessary drivers, configurations, services together into the image. However, the user OS image could be very large and cannot leave enough spaces for the following testing. That's why I want to specify OS disk size.

Regards,
Shuai Zhang

**Comment by adityagesh** [comment]
Hi,

Runbook already has support to override OS Disk Size.
Sample: 

```
platform:
  - type: azure
    azure:
      subscription_id: *******************
    requirement:
      azure:
        marketplace: *******
        location: *********
        osdisk_size_in_gb: 30
```
