### ISSUE TITLE
azure_deploy transformer doesn't respect source_address_prefixes and resource_group_name

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#3854]
Please set source_address_prefixes and resource_group_name if users set them in the runbook. Please add code in lisa\sut_orchestrator\azure\transformers.py

```
transformer:
  - type: azure_deploy
    name: build_vm
    phase: init
    resource_group_name: lisa-test-2025-6-12-001
    deploy: true
    source_address_prefixes: $(source_address_prefixes)
    requirement:
      azure:
        marketplace: $(marketplace_image)
```
